-- Constraints - Foreign Key  --

CREATE TABLE TB_ENDERECO
(
	EnderecoID INT IDENTITY(1,1),
	Logradouro VARCHAR(50),
	Numero VARCHAR(20),
	Bairro VARCHAR(15),
	CEP VARCHAR(15),
	ClienteID INT,
	CONSTRAINT PK_ENDERECO_EnderecoID PRIMARY KEY(EnderecoID),
	CONSTRAINT FK_ENDERECO_CLIENTE_CLIENTEID FOREIGN KEY(ClienteID)
)

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT FK_ENDERECO_CLIENTE_ClienteID FOREIGN KEY(ClienteID)
REFERENCES TB_CLIENTE(ClienteID)