-- Constraints - Primary Key, Unique --
CREATE TABLE TB_PRODUTO
(
	ProdutoID INT identity(1,1) --PRIMARY KEY NOT NULL
	CONSTRAINT PK_PRODUTO PRIMARY KEY ( ProdutoID )
)

ALTER TABLE TB_PRODUTO
ADD CONSTRAINT PK_PRODUTO PRIMARY KEY(ProdutoID)

CREATE TABLE TB_CLIENTE
(
	CPF VARCHAR(12) NOT NULL,
	CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF)
)

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF)


-- Constraints - Check, Default --

CREATE TABLE TB_CLIENTE2
(
	Idade INT NOT NULL,
	DataCriacao DATETIME2 NOT NULL DEFAULT GETDATE(),
	CONSTRAINT CK_CLIENTE_IDADE CHECK(Idade> 16)
)

ALTER TABLE TB_CLIENTE2
ADD CONSTRAINT CK_CLIENTE_IDADE CHECK(Idade> 16)

ALTER TABLE TB_CLIENTE2
ADD CONSTRAINT DF_CLIENTE_DATACRIACAO DEFAULT(GETDATE()) FOR DataCriacao